//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Projects = new HashSet<Project>();
            this.AuthTokens = new HashSet<AuthToken>();
        }
    
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<AuthToken> AuthTokens { get; set; }
    }
}
